FROM docker://nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu128
ENV CUDA_HOME="/usr/local/cuda"

RUN apt update && apt install -y python3 python3-pip python3-venv git cmake && apt clean

RUN python3 -m pip install --break-system-packages tox torch

ENV Torch_DIR=/usr/local/lib/python3.12/dist-packages/torch/share/cmake/Torch/
